var = input("Digite algo: ")
print("O tipo primitivo é ", type(var))
print("Só tem espaços: ", var.isspace())
print("Só tem numero: ", var.isnumeric())
print("É ordem alfabetica: ", var.isalpha())
print("É numerico: ", var.isalnum())
print("Está em maiusculas: ", var.isupper())
print("Está em minusculas: ", var.islower())
